### ISSUE TITLE
项目前端代码

### ISSUE THREAD

**Issue by FunnyWolf** [ice-doom/EyeJo#1]
你好,项目是前后端分离的吗?仓库中好像没有看到前端代码

**Comment by kiang70** [comment]
项目是基于django的，前端在每个app的templets目录。

**Comment by FunnyWolf** [comment]
只在这里看到了打包后的js代码 https://github.com/ice-doom/EyeJo/tree/main/eyejo/plugin/dist 是基于umi的 ,前端不开源吗?
