### ISSUE TITLE
端口过多会卡死

### ISSUE THREAD

**Issue by lovelyjuice** [ice-doom/EyeJo#11]
某些安全设备检测到端口扫描后会给所有SYN包回复ACK确认（比如阿里云），不管端口是否开放，导致eyejo认为扫描的主机所有端口均开放，直接把浏览器卡死。。。并且导致后续任务无法继续。如果开放的端口大于一定数量，应放弃对这个IP的扫描，以免影响扫描进度。

**Comment by ice-doom** [comment]
默认情况下，扫描端口结果数量超过400，会重新扫描少量端口的，在[portscan.py](https://github.com/ice-doom/EyeJo/blob/main/eyejo/plugin/portscan/portscan.py)的`waf_port`有进行判断。目前是查看日志发现卡死的么，能否提供截图信息。

**Comment by lovelyjuice** [comment]
是把浏览器卡死，网页还没渲染出来就无响应了

**Comment by ice-doom** [comment]
是一直卡住？这块代码做了超时处理的，理论上应该不会，提供下日志的截图信息。
`docker exec -it eyejo_worker tail -100 celery.log`

**Comment by lovelyjuice** [comment]
后端没有卡死，只是大大延缓了扫描进度，前端应该是js拉取数据填充表格的时候卡死的

**Comment by ice-doom** [comment]
哦，我以为说的是后端调用Chromium卡死。那提供下开发者模式的Network以及浏览器卡死的截图，理论上应该不会卡死，因为有分页处理最多就100个。
