### ISSUE TITLE
支持xray报告导出

### ISSUE THREAD

**Issue by zhangleisec** [ice-doom/EyeJo#12]
扫描完成后 支持xray报告导出

**Comment by ice-doom** [comment]
这个要做的话，需要改动的是保存到容器中拷贝出来，或者映射到本地一个文件夹中保存。支持前端导出要延后

**Comment by ice-doom** [comment]
重新拉取镜像，目前xray的html报告存放在容器中，以任务名命名。可以使用下面命令拷贝出来
`docker cp eyejo_worker:/root/eyejo/plugin/crawl_to_xray/data/t1-新建任务.html .`
