### ISSUE TITLE
目前只有站点详情处可以导出，请问于域名处能否支持导出

### ISSUE THREAD

**Issue by kesonn** [ice-doom/EyeJo#13]
![image](https://user-images.githubusercontent.com/36539433/120337112-9a9b3000-c325-11eb-96a7-3f567281bf54.png)

**Comment by ice-doom** [comment]
站点详情处的导出，有域名信息。可以导出查看效果

**Comment by kesonn** [comment]
![image](https://user-images.githubusercontent.com/36539433/120356047-80b61900-c336-11eb-8c5b-b43aa3d3818f.png)
站点的数量有点少哇～～

**Comment by ice-doom** [comment]
请求站点任务是否跑完。跑完仍出现这种情况的话，先确认下配置并发是否过大，默认情况下是20。

**Comment by kesonn** [comment]
跑完了的
![image](https://user-images.githubusercontent.com/36539433/120505451-93445700-c3f7-11eb-8973-02f6020078ef.png)

![image](https://user-images.githubusercontent.com/36539433/120505520-9fc8af80-c3f7-11eb-933d-cf6a19d1099e.png)

**Comment by ice-doom** [comment]
可以尝试对该资产组重新使用请求站点功能跑一遍。
要么就是确实目标不可访问，可以再资产组筛选状态为unaccess查看到不可访问的URL
