### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by KangD1W2** [ice-doom/EyeJo#15]
建议增加暂停后出现启动扫描的功能，并且增加导出全部站点漏洞信息的功能

**Comment by ice-doom** [comment]
目前更新的话，时间会延后。本来考虑的就是漏洞信息放在平台展示，没有做出导出功能。这个功能添加排序会放在后面完成。

**Comment by ketchup1995** [comment]
什么时候更新资产监控

**Comment by hqdun69** [comment]
项目设置那块设置一次就行了么

**Comment by ice-doom** [comment]
> 项目设置那块设置一次就行了么

项目设置那里前端有个bug，第一次启动项目时打开页面没有加载默认配置，需要刷新才能看到。
进行设置提交后就可以了。

**Comment by ice-doom** [comment]
@ketchup1995 资产监控优先级比较靠后，fofa的自定义搜索优先级高些，添加项目前端处再加fofa有点臃肿，都还没定下来。

**Comment by fsocietyon** [comment]
![1629253751(1)](https://user-images.githubusercontent.com/49747255/129826973-ff62fd95-8cd2-4cc2-9dae-34f37e4059a0.jpg)
这个启动时候报错是什么问题啊？

**Comment by ice-doom** [comment]
@fsocietyon 新开个issues吧。
这个是通过docker-compose启动的么
