### ISSUE TITLE
内容有误 

### ISSUE THREAD

**Issue by trh812** [ice-doom/EyeJo#17]
其中访问为https ，非http

**Comment by ice-doom** [comment]
项目启动后是访问https的，有什么问题，可以把细节贴出来

**Comment by trh812** [comment]
![image](https://user-images.githubusercontent.com/48972652/128667333-ed38fe20-a9bc-45b4-a88d-114c0850f4a3.png)
你的内容上是访问是http 访问 但实际上是https访问
