### ISSUE TITLE
漏洞检测建议

### ISSUE THREAD

**Issue by aa506** [ice-doom/EyeJo#21]
在漏洞检测后，结果列表中显示了，url｜payload | 请求数据 | 漏洞类型

建议将返回信息打印出来，例如存在报错注入，就可以在返回信息中查看报错哪些东西了。

![iShot2021-09-12 01 17 18](https://user-images.githubusercontent.com/29257678/132955912-79d773fe-2d11-4335-9258-6c6c5921aae9.png)

**Comment by ice-doom** [comment]
有的时候响应包数据很大，展示的效果不好。可以复制请求包到burp重放，或者查看xray报告，参考[issues#12](https://github.com/ice-doom/EyeJo/issues/12)
