### ISSUE TITLE
项目设置-设置api那里不能提交

### ISSUE THREAD

**Issue by zjhzjhhh** [ice-doom/EyeJo#25]
师傅，设置api那里点击提交无效，一直没有反应
![image](https://user-images.githubusercontent.com/64487620/201385089-c2936bcb-3777-49c7-8f6a-4fc83c1ac849.png)

**Comment by ice-doom** [comment]
fofa的api那里，是老接口了，可能现在更新了，已经不能用了。
提交点击之后，有看到发送请求了么，如果没有可能是前端问题。可以刷新几次试试。
IP处未打码

**Comment by zjhzjhhh** [comment]
> 师傅，设置api那里点击提交无效，一直没有反应 ![image](https://user-images.githubusercontent.com/64487620/201385089-c2936bcb-3777-49c7-8f6a-4fc83c1ac849.png)
