### ISSUE TITLE
IP扫描问题

### ISSUE THREAD

**Issue by xtzxtz** [ice-doom/EyeJo#3]
请问，在进行项目添加时添加如127.0.0.1这类型IP地址，总是出现域名格式错误的提示，是不是现在不能进行单IP地址的扫描

**Comment by ice-doom** [comment]
单个IP目前可以通过192.168.1.1/32这种方式添加，后续优化下，尽量支持单个IP情况不需要加上掩码

**Comment by ice-doom** [comment]
关于单个IP问题，docker已经更新，可以试用
