### ISSUE TITLE
在项目管理者删除后有个小bug

### ISSUE THREAD

**Issue by TheTh1nk3r** [ice-doom/EyeJo#6]
删除后不会更新页面，要手动刷新删除的才会消失
![image](https://user-images.githubusercontent.com/42456962/117794378-c4f65200-b27f-11eb-8e0e-615b6430aae6.png)

**Comment by ice-doom** [comment]
好，这个我记录下来

**Comment by gusechuisheng** [comment]
老哥，我pull下来不会用了，启动了也访问不了

**Comment by ice-doom** [comment]
> 老哥，我pull下来不会用了，启动了也访问不了

可以执行docker ps -a看看容器是否启动成功，端口是否侦听

**Comment by gusechuisheng** [comment]
root@ubuntu:~# docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                                     NAMES
6e6e3a9749f8   mirchdocker/eyejo:latest   "sh -c 'python3 mana…"   26 minutes ago   Up 21 minutes   0.0.0.0:6103->443/tcp, :::6103->443/tcp   eyejo_ubuntu
08fb7670ec2d   mirchdocker/eyejo:latest   "sh -c 'celery -A Ey…"   26 minutes ago   Up 21 minutes                                             eyejo_worker

root@ubuntu:~# netstat -ano |grep 6103
tcp        0      0 0.0.0.0:6103            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp6       0      0 :::6103                 :::*                    LISTEN      off (0.00/0/0)

**Comment by ice-doom** [comment]
> root@ubuntu:~# docker ps
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 6e6e3a9749f8 mirchdocker/eyejo:latest "sh -c 'python3 mana…" 26 minutes ago Up 21 minutes 0.0.0.0:6103->443/tcp, :::6103->443/tcp eyejo_ubuntu
> 08fb7670ec2d mirchdocker/eyejo:latest "sh -c 'celery -A Ey…" 26 minutes ago Up 21 minutes eyejo_worker
> 
> root@ubuntu:~# netstat -ano |grep 6103
> tcp 0 0 0.0.0.0:6103 0.0.0.0:* LISTEN off (0.00/0/0)
> tcp6 0 0 :::6103 :::* LISTEN off (0.00/0/0)

是有启动成功的，访问https://127.0.0.1:6103/不行？

**Comment by gusechuisheng** [comment]
> > root@ubuntu:~# docker ps
> > CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> > 6e6e3a9749f8 mirchdocker/eyejo:latest "sh -c 'python3 mana…" 26 minutes ago Up 21 minutes 0.0.0.0:6103->443/tcp, :::6103->443/tcp eyejo_ubuntu
> > 08fb7670ec2d mirchdocker/eyejo:latest "sh -c 'celery -A Ey…" 26 minutes ago Up 21 minutes eyejo_worker
> > root@ubuntu:~# netstat -ano |grep 6103
> > tcp 0 0 0.0.0.0:6103 0.0.0.0:* LISTEN off (0.00/0/0)
> > tcp6 0 0 :::6103 :::* LISTEN off (0.00/0/0)
> 
> 是有启动成功的，访问[https://127.0.0.1:6103/不行？](https://127.0.0.1:6103/%E4%B8%8D%E8%A1%8C%EF%BC%9F)

嗯不行

**Comment by gusechuisheng** [comment]
老哥，现在好了，连接不了数据库，修改账号密码。

**Comment by ice-doom** [comment]
数据库默认密码是eyejo@pass，在docker-compose.yml中可以查看

**Comment by hawk-520** [comment]
安装完成访问出现400错误
