### ISSUE TITLE
IP信息收集方式里面的两种方式，请问可以解释一下吗

### ISSUE THREAD

**Issue by kesonn** [ice-doom/EyeJo#8]
IP信息收集方式里面的两种方式，请问可以解释一下吗

**Comment by kesonn** [comment]
gettitle2和ip-api，具体指的是啥

**Comment by ice-doom** [comment]
这两个都是对输入、收集到的IP来获取地理位置信息和ASN等。ip-api是调用的第三方接口数据获取（数据新、大部分都能获取到数据、但是慢，这是国外的数据来源）、gettitle2是离线库里获取（有的IP可能没有数据，速度快）。

**Comment by kesonn** [comment]
ok，谢谢大佬

**Comment by ice-doom** [comment]
close
